# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPutDownAndIn <- function(nInt = 100L, Strike = 100, Spot = 95, Vol = 0.2, Rfr = 0.06, Expiry = 0.5, nReps = 100L) {
    .Call(`_BKput_getPutDownAndIn`, nInt, Strike, Spot, Vol, Rfr, Expiry, nReps)
}

