# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDownInPutPrice <- function(Expiry = 0.5, Strike = 100, Spot = 95, Vol = 0.2, r = 0.06, nReps = 100L) {
    .Call(`_BKput_getDownInPutPrice`, Expiry, Strike, Spot, Vol, r, nReps)
}

